package com.amolina.domain.model

import com.example.example.Ratings
import com.google.gson.annotations.SerializedName

data class Data(

    @SerializedName("pics_main") var picsMain: PicsMain? = PicsMain(),
    @SerializedName("pics_diaporama") var picsDiaporama: ArrayList<PicsDiaporama> = arrayListOf(),
    @SerializedName("restaurant_tags") var restaurantTags: RestaurantTags? = RestaurantTags(),
    @SerializedName("highlighted_tag") var highlightedTag: ArrayList<HighlightedTag> = arrayListOf(),
    @SerializedName("ratings") var ratings: Ratings? = Ratings(),
    @SerializedName("yums_detail") var yumsDetail: YumsDetail? = YumsDetail(),
    @SerializedName("michelin_detail") var michelinDetail: MichelinDetail? = MichelinDetail(),
    @SerializedName("id_restaurant") var idRestaurant: Int? = null,
    @SerializedName("restaurant_uuid") var restaurantUuid: String? = null,
    @SerializedName("name") var name: String? = null,
    @SerializedName("portal_url") var portalUrl: String? = null,
    @SerializedName("gps_lat") var gpsLat: Double? = null,
    @SerializedName("gps_long") var gpsLong: Double? = null,
    @SerializedName("address") var address: String? = null,
    @SerializedName("id_city") var idCity: Int? = null,
    @SerializedName("city") var city: String? = null,
    @SerializedName("id_city_zipcode") var idCityZipcode: Int? = null,
    @SerializedName("zipcode") var zipcode: String? = null,
    @SerializedName("id_country") var idCountry: Int? = null,
    @SerializedName("country") var country: String? = null,
    @SerializedName("locale_code") var localeCode: String? = null,
    @SerializedName("phone") var phone: String? = null,
    @SerializedName("public_phone") var publicPhone: String? = null,
    @SerializedName("email") var email: String? = null,
    @SerializedName("obfuscated_email") var obfuscatedEmail: String? = null,
    @SerializedName("rate_count") var rateCount: Int? = null,
    @SerializedName("currency_code") var currencyCode: String? = null,
    @SerializedName("min_price") var minPrice: Int? = null,
    @SerializedName("min_price_before") var minPriceBefore: Int? = null,
    @SerializedName("web_max_days") var webMaxDays: Int? = null,
    @SerializedName("is_lf_test_restaurant") var isLfTestRestaurant: Int? = null,
    @SerializedName("is_published_affiliate") var isPublishedAffiliate: Int? = null,
    @SerializedName("is_published_portal") var isPublishedPortal: Int? = null,
    @SerializedName("is_phone_displayed") var isPhoneDisplayed: Int? = null,
    @SerializedName("card_price") var cardPrice: Int? = null,
    @SerializedName("id_restaurant_tag_speciality") var idRestaurantTagSpeciality: Int? = null,
    @SerializedName("id_restaurant_tag_speciality_category") var idRestaurantTagSpecialityCategory: Int? = null,
    @SerializedName("speciality") var speciality: String? = null,
    @SerializedName("id_sale_type_normal") var idSaleTypeNormal: Int? = null,
    @SerializedName("avg_rate_evolution") var avgRateEvolution: String? = null,
    @SerializedName("chef_name") var chefName: String? = null,
    @SerializedName("menu_external_link") var menuExternalLink: String? = null,
    @SerializedName("description") var description: String? = null,
    @SerializedName("hour_open") var hourOpen: String? = null,
    @SerializedName("vacation") var vacation: String? = null,
    @SerializedName("transport") var transport: String? = null,
    @SerializedName("parking") var parking: String? = null,
    @SerializedName("other_localization_infos") var otherLocalizationInfos: String? = null,
    @SerializedName("nb_max_group") var nbMaxGroup: Int? = null,
    @SerializedName("insider_description") var insiderDescription: String? = null,
    @SerializedName("insider_tips") var insiderTips: String? = null,
    @SerializedName("card_start_1") var cardStart1: String? = null,
    @SerializedName("card_start_2") var cardStart2: String? = null,
    @SerializedName("card_start_3") var cardStart3: String? = null,
    @SerializedName("card_main_1") var cardMain1: String? = null,
    @SerializedName("card_main_2") var cardMain2: String? = null,
    @SerializedName("card_main_3") var cardMain3: String? = null,
    @SerializedName("card_dessert_1") var cardDessert1: String? = null,
    @SerializedName("card_dessert_2") var cardDessert2: String? = null,
    @SerializedName("card_dessert_3") var cardDessert3: String? = null,
    @SerializedName("price_half_bottle_of_mineral_water") var priceHalfBottleOfMineralWater: Int? = null,
    @SerializedName("price_bottle_of_mineral_water") var priceBottleOfMineralWater: Int? = null,
    @SerializedName("price_bottle_of_wine_max") var priceBottleOfWineMax: Int? = null,
    @SerializedName("price_bottle_of_wine_min") var priceBottleOfWineMin: Int? = null,
    @SerializedName("price_of_coffee") var priceOfCoffee: Int? = null,
    @SerializedName("trip_advisor_avg_rating") var tripAdvisorAvgRating: Int? = null,
    @SerializedName("trip_advisor_review_count") var tripAdvisorReviewCount: Int? = null,
    @SerializedName("is_amex") var isAmex: Boolean? = null,
    @SerializedName("has_stock") var hasStock: Int? = null,
    @SerializedName("is_opened") var isOpened: Int? = null

)